name: CI

on:
  push:
    branches:
      - qio
    paths-ignore:
      - '**.md'
      - '**/CD.yml'
      - '**/nightly.yml'
      - './*.yml'

env:
  UPLOAD_BUILD: true

jobs:
  CodeCheck:
    name: CodeCheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        enable: all #performance,portability,warning
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          # - "bg96_amazon_mqtt"
          - "bg96_client_http"
          - "bg96_dss_dns"
          - "bg96_gps"
          - "bg96_i2c_Si7021"
          # - "bg96_hello_world"
          # - "bg96_PubSubClient"
          # - "coap_basic"
          # - "tcp_http"
          # - "timers"
          - "BC66_A1_HELLO"
          - "BC66_A2_CLIENT_TCP"
          - "BC66_A3_CLENT_HTTP"
          - "BC66_A4_MQTT"
          - "BC66_A5_PSM"
          - "BC66_A6_MQTT_SECURE"
          # - "BC66_A7_PubSub"
          # - "BC66_A8_OLED_I2C"
          - "BC66_A9_SI7021"
          # - "BC66_A10_DS1820_OLED"
          - "BC66_A11_DS1820_DHT_GPIO"
          - "BC66_A12_Ultrasonic_HCSR04_SPI"
          - "BC66_CPP_HELLO"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install file://.

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}
          echo "::set-output name=status::success"

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: pio_${{ matrix.example }}_${{ matrix.os }}
          path: examples/${{ matrix.example }}/.pio/build

  pio_pass:
    needs:
      - QIO
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO success"

  pio_fail:
    needs:
      - QIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO failure"
